#!/usr/bin/env python
# Generates a C preprocessor macro for "unrolling a loop". Useful for looping
# over assembler labels.

print('/* Generated by scripts/make-repeat.h.py */')
print('#ifndef _INCLUDE_REPEAT_H')
print('#define _INCLUDE_REPEAT_H')
print('#define REPEAT_0(M) M(0)')
for i in range(1, 256):
    print('#define REPEAT_{}(M) M({}) REPEAT_{}(M)'.format(i, i, i - 1))
print('#endif')
